// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfipxpoypivbiraavtkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmaXB4cG95cGl2YmlyYWF2dGt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NjcwMDYsImV4cCI6MjA3MTQ0MzAwNn0.1V-bKiqLMengCWlNku0j7UzJJiHq9TodJ-yEL9iRJTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});